server.port: 8080
spring.application.name: spring-cloud-gateway
server.servlet.context-path: /gateway
management:
  endpoints:
    web:
      exposure:
        include: health, info
    health:
      show-details: never
      probes.enabled: true
eureka:
  client:
    region: eu-west-1
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
          predicates:
            - name: Path
              args:
                pattern: "'/gateway/' + serviceId + '/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'/gateway/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://host.docker.internal:9000/realms/dev/protocol/openid-connect/token/introspect
          client-id: dev-cli
          client-secret:
        jwt:
          jwk-set-uri: http://host.docker.internal:9000/realms/dev/protocol/openid-connect/certs
          issuer-uri: http://host.docker.internal:9000/realms/dev